# Generated by Django 4.1.2 on 2022-10-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_order_quantity_remove_order_shoppingcart_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_id',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
